---
spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: false
        show_sql: true
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL92Dialect

  jackson:
    deserialization:
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true

  liquibase:
    enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:}
    username: uulmmrgtokbnwa
    password: 0e3e8f3e016029d1d800bd85b4b302fc005394031f6e8780d08e1a6eb626430d
#    url: jdbc:postgresql://localhost:5432/postgres?reWriteBatchedInserts=true
#    username: postgres
#    password: postgres


management:
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics, mappings, prometheus
  endpoint:
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full

#cake-project: